### ISSUE TITLE
Major Bug: Data input for merging template is of a static structure

### ISSUE THREAD

**Issue by gstewart-aiwyn** [pdfgeneratorapi/java-client#3]
When calling the merge template function, there is a required parameter of type, Data. Data has fields **id** and **name** which I'm assuming were just dummy fields for an example template. This essentially make the client library useless as you can't use it to merge templates with any other data structure. 

![image](https://user-images.githubusercontent.com/84802918/163750381-0469388d-a612-48a3-bacd-372f87fafc57.png)

**Comment by pdfgeneratorapi** [comment]
Hi! You are correct; id and name are dummy fields autogenerated based on the API documentation. You can extend the Data class and specify your data structure.

**Comment by gstewart-aiwyn** [comment]
Gotcha, I just figured it was weird to extend on a class that has fields that won't be used. Should be workable though. Thanks!
